system:
  db_file: 1Panel.db
  base_dir: /opt
  mode: stable
  repo_url: https://resource.fit2cloud.com/1panel/package
  CustomUpgradeCheckURL: https://github.com/gcsong023/wrt1panel/releases
  app_repo: https://apps-assets.fit2cloud.com
  is_demo: false
  port: 9999
  username: admin
  password: admin123

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: 1Panel
  log_suffix: .log
  max_backup: 10
